### ISSUE TITLE
What is `Block content on any page` permission for?

### ISSUE THREAD

**Issue by solzard** [rNeomy/reader-view#164]
Reader View version 0.7.0 requested `Block content on any page` permission. What's this for? Would you mind clarifying the purpose and usage, please?

Environment:
Reader View: 0.7.0
Brave Browser: 1.48.164 Chromium: 110.0.5481.100 (Official Build) (arm64)
macOS: 12.6.3 (21G419)

![Screenshot 2023-02-22 at 16 28 42](https://user-images.githubusercontent.com/29563481/220552125-75b46701-f879-4a17-8e38-120f72fd0288.jpg)

**Comment by rNeomy** [comment]
This message refers to the "declarativeNetRequest" permission authorization, which we require to substitute the "origin" and "referer" headers for remote TTS (Text-to-Speech) engines. Ideally, we intended to categorize this permission as optional since it's only necessary if the user intends to use remote voices. Nonetheless, it turned out that it's not possible to list this permission as optional!

https://github.com/rNeomy/reader-view/blob/master/v3/manifest.json#L13

**Comment by rNeomy** [comment]
I'm replacing the "declarativeNetRequest" permission with "declarativeNetRequestWithHostAccess." As a result, the warning message is no longer present!
